### ISSUE TITLE
Errors on Homepage

### ISSUE THREAD

**Issue by emmalou** [graphcool/graphql-europe-2018#1]
- [x] Date should be June 15th, 2018

- [x] Location should be nHow Hotel, Berlin

- [x] Button should say Get Tickets (instead of Get Ticket)

- [x] In the video section, wherever it says GraphQL Co-Creator, the Co-Creator should be capitalized

- [x] 100% *of attendees* said they would attend again

- [x] Add Sponsor pack (Johanna has design)

- [x] Remove sponsor logos 

- [ ] Add Footer with Code of Conduct, Imprint from 2017. Should be © GraphQL-Europe 2018

**Comment by morajabi** [comment]
OK, I fixed them all, except the footer. I'm going to close this issue and I'll make another issue just for the footer.
