### ISSUE TITLE
Get Tickets Button on Homepage Should Redirect to Tickets Section 

### ISSUE THREAD

**Issue by emmalou** [graphcool/graphql-europe-2018#10]

**Comment by morajabi** [comment]
One thing I just noticed, shouldn't we rename all buttons that redirect to tickets section to one name? We have: Get ticket and Register.

**Comment by emmalou** [comment]
Get Tickets is better.

Nice spot!

Am 24.10.2017 5:18 nachm. schrieb "Mohammad Rajabifard" <
notifications@github.com>:

**Comment by morajabi** [comment]
Also, What should I do with "Attend" item in the navbar?
