### ISSUE TITLE
Updates for Team page

### ISSUE THREAD

**Issue by Batjohe** [graphcool/graphql-europe-2018#18]
1. Change Kate's description to -> 
Ekaterina is a Growth Manager at Honeypot. Originally from Moscow, Kate moved to Amsterdam to study management in creative industries. With experience in advertising and cinema, she enjoys making events happen.

2. Change my picture to:
![johanna1](https://user-images.githubusercontent.com/16031257/32014709-298037c6-b9bf-11e7-9108-30dc9345f57b.png)

3. Change Emmas picture to 
![emma2](https://user-images.githubusercontent.com/16031257/32014441-66c12d94-b9be-11e7-960f-b03495aee06b.jpg)

4. Change Kate's picture to
![img_4022_top](https://user-images.githubusercontent.com/16031257/32014467-77e67494-b9be-11e7-83ad-e000b30991c6.jpg)

**Comment by morajabi** [comment]
Why are all of them B&W? If that's the style we need to change the other two. But that's my opinion. What do you think?

**Comment by Batjohe** [comment]
we can change them to b&w :)

**Comment by morajabi** [comment]
EKATERINA's pic is the same!

**Comment by morajabi** [comment]
I can't b&w them now since they're very low quality if I do that, they'll be awful! We should get HQ photos from them.
